export interface Scheduling {
    agendamento_id?: number,
    paciente_id: number,
    tipo_encaminhamento_id: number,
    tipo_doenca_id: number,
    tipo_remocao_id: number,
    hospital_id: number,
    veiculo_id: number,
    motorista_id: number,
    responsavel_pac: string,
    data_remocao: Date,
    saida_prevista: Date,
    observacao: string,
    custo_ifd: number,
    custo_estadia: number,
    estado_geral_paciente: string,
}

export interface SchedulingFull {
    agendamento_id?: number,
    nome: string,
    hygia: string,
    tel_1: string,
    data_nascimento: Date,
    data_remocao: Date,
    saida_prevista: Date,
    hospital: string,
    tipo_encaminhamento: string,
    tipo_doenca: string,
    tipo_remocao: string,
    veiculo_modelo: string,
    veiculo_placa: string,
    veiculo_capacidade: string,
    veiculo_media_consumo: string,
    usuario: string,
    motorista: string,
    responsavel_pac: string,
    estado_geral_paciente: string,
    observacao: string,
    custo_ifd: number,
    custo_estadia: number
}